#!/bin/bash

place=$(pwd)
echo "Installing requirements.txt"
# Install requirements in the virtual environment
source venv/bin/activate  # Activate the virtual environment
pip install -r requirements.txt
apt-get install -y chromium
deactivate  # Deactivate the virtual environment


echo "running the script v4 inside $place"
sleep 2


PID=$(cat /root/automation/run.pid)
echo "killing the existing nohup process"
sleep 2
kill -9 $PID
echo "nohup process killed"




echo "restarting nohup with new changes"
nohup venv/bin/python3 main.py > /root/automation/output.log 2> /dev/null &

echo $! > /root/automation/run.pid
echo " nohup started with PID: $!"

